Buy product
tarikkaa/juice-shop-test pull request #6
Opened 2022-10-07 07:42 UTC by tarikkaa

2022-10-07 14:58 UTC, nbabii requested changes

2022-10-07 14:58 UTC, nbabii commented on pages/addAddressPage.js
> +    get stateField() {return new InputElement($('(//div/mat-card//input)[6]'), "State input field")};
Ті ікспасні локатори шось мені не дуже, ми можем використовувати локатори з індексами, але рідко. Глянь чи там може є якісь класи проперті до яких привязатись

2022-10-07 14:58 UTC, nbabii commented on pages/deliveryAddressPage.js
> +    get continueButton() {return new WebButton($('//div/button[2]'), "Continue button of the Delivery address page")};
локатор ліпше інший

2022-10-07 14:58 UTC, nbabii commented on test/specs/buy_product.js
> +  };
оті всі рендом генерагтори винеси в окремий файл, імпортай його де треба і юзай.
назми його якось randomHelpper

2022-10-08 17:28 UTC, tarikkaa commented on pages/deliveryAddressPage.js
> +    get continueButton() {return new WebButton($('//div/button[2]'), "Continue button of the Delivery address page")};
який саме локатор ти маєш на увазі? тут їх 4шт. на скріні

2022-10-10 12:38 UTC, nbabii commented on pages/deliveryAddressPage.js
> +    get continueButton() {return new WebButton($('//div/button[2]'), "Continue button of the Delivery address page")};
//div/button[2] - то саме шо в коменті вище "Ті ікспасні локатори шось мені не дуже, ми можем використовувати локатори з індексами, але рідко. Глянь чи там може є якісь класи проперті до яких привязатись"

2022-10-10 12:43 UTC, tarikkaa commented on pages/deliveryAddressPage.js
> +    get continueButton() {return new WebButton($('//div/button[2]'), "Continue button of the Delivery address page")};
затяни зміни, вже мало бути ок

2022-10-11 16:00 UTC, nbabii requested changes

2022-10-11 16:00 UTC, nbabii commented on pages/addAddressPage.js
> +    get stateField() {return new InputElement($('input[placeholder*="state"]'), "State input field")};
плейсхолдер не міняється якшо в полі є текст? бо таке враження шо локатор не буде працювати якшо в поле втайпаний текст

2022-10-11 16:30 UTC, tarikkaa commented on pages/addAddressPage.js
> +    get stateField() {return new InputElement($('input[placeholder*="state"]'), "State input field")};
плейсхолдер не міняється якшо в полі є текст/ всьо гуд

2022-10-11 16:30 UTC, merged