Added TC: Buy the item that Only 1 left
tarikkaa/juice-shop-test pull request #8
Opened 2022-10-11 18:20 UTC by tarikkaa

2022-10-11 19:15 UTC, nbabii requested changes

2022-10-11 19:15 UTC, nbabii commented on pages/homePage.js
> +    async addToBasketOnlyOneLeft() {
Зроби метод який буде вибирати продукт по імені яке ти передаєш і тоді в нього передавай імя продукту який залишився тіки один

2022-10-11 19:15 UTC, nbabii commented on test/specs/buy_product.js
> +        chaiExpect(await orderCompletionPage.getPageTitle()).to.equal("Thank you for your purchase!");
тут треба перевірку шо той продукт вже не доступний після того як ти останній купив

2022-10-11 19:49 UTC, tarikkaa commented on pages/homePage.js
> +    async addToBasketOnlyOneLeft() {
зробив

2022-10-11 19:49 UTC, tarikkaa commented on test/specs/buy_product.js
> +        chaiExpect(await orderCompletionPage.getPageTitle()).to.equal("Thank you for your purchase!");
зробив

2022-10-12 13:11 UTC, nbabii approved these changes

2022-10-12 13:11 UTC, merged