Added TCs for the customer feedback page
tarikkaa/juice-shop-test pull request #9
Opened 2022-10-19 21:22 UTC by tarikkaa

2022-10-19 21:58 UTC, nbabii requested changes

2022-10-19 21:58 UTC, nbabii commented on elements/slider.element.js
> +        console.log(location);
ти береш локейшн просто шоб в консоль вивести? може тре його повертати)

2022-10-24 16:37 UTC, tarikkaa commented on elements/slider.element.js
> +        console.log(location);
то довбався з тим слайдером, перероблю

2022-10-24 16:44 UTC, tarikkaa commented on elements/slider.element.js
> +        console.log(location);
зробив

2022-10-24 17:03 UTC, nbabii approved these changes

2022-10-24 18:42 UTC, merged